/* 原始题池 — 由 3 个子 agent 生成，~150 道新题。
   build.js 会做类型校验后混合到 quizzes.js。 */

const NEWPOOL = [

/* === 段 A：进制 / CA2 / 浮点 === */
{topic: "base", difficulty: 2, type: "fill", points: 2, q: "将十进制数 $(47)_{10}$ 转换为二进制（不含括号）。", answer: "101111", explain: "47÷2 余 1, 23÷2 余 1, 11÷2 余 1, 5÷2 余 1, 2÷2 余 0, 1÷2 余 1，自下而上读 $(101111)_2$。"},
{topic: "base", difficulty: 2, type: "mcq", points: 2, q: "$(1011.101)_2$ 转十进制 = ?", options: ["11.625", "12.625", "10.5", "11.5"], answer: 0, explain: "$8+2+1+0.5+0.125 = 11.625$"},
{topic: "base", difficulty: 2, type: "fill", points: 2, q: "$(1101)_2$ 转十进制 = ?", answer: "13", explain: "$8+4+0+1 = 13$"},
{topic: "base", difficulty: 2, type: "mcq", points: 2, q: "$(0.625)_{10}$ 转二进制 = ?", options: ["$(0.101)_2$", "$(0.110)_2$", "$(0.111)_2$", "$(0.011)_2$"], answer: 0, explain: "$0.625\\times 2=1.25 → 1$；$0.25\\times 2=0.5 → 0$；$0.5\\times 2=1.0 → 1$。"},
{topic: "base", difficulty: 3, type: "fill", points: 3, q: "$(2AC.B)_{16}$ 转二进制（不含小数点前导 0 限制）", answer: "1010101100.1011", explain: "每位十六进制 → 4 位：$2=0010, A=1010, C=1100, B=1011$。"},
{topic: "base", difficulty: 3, type: "judge", points: 2, q: "$5/8$ 在二进制中有有限表示。", answer: true, explain: "$8 = 2^3$；分母质因子 $\\{2\\} \\subseteq \\{2\\}$ ⇒ 有限。"},
{topic: "base", difficulty: 3, type: "judge", points: 2, q: "$1/3$ 在十进制中有有限表示。", answer: false, explain: "分母含 3 ∉ {2,5}。"},
{topic: "base", difficulty: 3, type: "mcq", points: 2, q: "下列哪个分数在二进制中无有限表示？", options: ["$1/16$", "$3/8$", "$1/5$", "$7/4$"], answer: 2, explain: "$1/5$ 分母含 5 ∉ {2}。"},
{topic: "base", difficulty: 3, type: "judge", points: 2, q: "$(0.408)_{10}$ 在二进制中有有限表示。", answer: false, explain: "$0.408 = 51/125$；$125=5^3$ ⇒ 无限。"},
{topic: "base", difficulty: 3, type: "mcq-multi", points: 3, q: "下列哪些数在六进制中有有限表示？", options: ["$1/3$", "$1/4$", "$1/9$", "$5/12$"], answer: [0, 2, 3], explain: "$6 = 2\\times 3$；$1/3$ ✓；$1/4 = 1/2^2$，需 4 ∉ 因子集 ✗；$1/9 = 1/3^2$ ✓；$5/12 = 5/(2^2\\cdot 3)$ ✓。"},
{topic: "base", difficulty: 4, type: "fill", points: 3, q: "$(0.2)_8$ 转二进制 = ?", answer: "0.010", explain: "$2_8 = (010)_2$。"},
{topic: "base", difficulty: 4, type: "fill", points: 3, q: "$(0.65625)_{10}$ 转二进制（精度 $2^{-5}$）= ?", answer: "0.10101", explain: "$0.65625\\times 2 = 1.3125 → 1$；$0.3125\\times 2 = 0.625 → 0$；$0.625\\times 2 = 1.25 → 1$；$0.25\\times 2 = 0.5 → 0$；$0.5\\times 2 = 1 → 1$。"},
{topic: "base", difficulty: 5, type: "subjective", points: 4, q: "为何 $(0.1)_{10}$ 在二进制中无限循环？与浮点舍入误差有何关系？", answer: "分母 $10 = 2\\cdot 5$ 含 5 ⇒ 无限循环。浮点舍入截断 → 经典 $0.1+0.2 \\neq 0.3$。", explain: "$5 \\nmid 2$ ⇒ 无有限二进制；浮点必舍入，累积误差。"},
{topic: "base", difficulty: 5, type: "subjective", points: 4, q: "证明 $(0.\\overline{142857})_{10} = 1/7$ 并判断在二进制中是否有限。", answer: "$x = 142857/999999 = 1/7$；$7 \\nmid 2$ ⇒ 二进制无限。", explain: "周期 6 ⇒ 分母 $10^6-1 = 999999 = 7\\cdot 142857$。"},

{topic: "ca2", difficulty: 2, type: "fill", points: 2, q: "8 位补码表示范围（写成 $a, b$ 形式）：", answer: "-128,127", explain: "$[-2^{k-1}, 2^{k-1}-1]$。"},
{topic: "ca2", difficulty: 2, type: "mcq", points: 2, q: "$+42$ 的 8 位 CA2 = ?", options: ["00101010", "10101010", "11010110", "01010101"], answer: 0, explain: "正数直接二进制。"},
{topic: "ca2", difficulty: 2, type: "fill", points: 2, q: "$-42$ 的 8 位 CA2 = ?", answer: "11010110", explain: "$42=00101010$；取反 $11010101$；+1 $11010110$。"},
{topic: "ca2", difficulty: 2, type: "mcq", points: 2, q: "16 位 CA2 范围 = ?", options: ["$[-32768, 32767]$", "$[-32767, 32768]$", "$[-65536, 65535]$", "$[-32768, 32768]$"], answer: 0, explain: "$[-2^{15}, 2^{15}-1]$。"},
{topic: "ca2", difficulty: 3, type: "judge", points: 2, q: "CA2 自反性 $\\text{CA2}(\\text{CA2}(x)) = x$ 对所有 8 位值成立。", answer: true, explain: "取反 + 1 两次回到原值（mod $2^8$ 自动）。"},
{topic: "ca2", difficulty: 3, type: "mcq", points: 3, q: "8 位 CA2 码 $(11110000)_2$ 对应十进制 = ?", options: ["-16", "-240", "-128", "-15"], answer: 0, explain: "首位 1 → 取反+1：$(00010000) = 16$ ⇒ $-16$。"},
{topic: "ca2", difficulty: 3, type: "judge", points: 2, q: "8 位 CA2 中 $-64 + (-64)$ 会溢出。", answer: false, explain: "$-128 \\in [-128, 127]$ 可表 ⇒ 不溢出。$11000000 + 11000000 = 1\\,10000000$ 截 $10000000 = -128$。"},
{topic: "ca2", difficulty: 3, type: "mcq", points: 3, q: "下列 8 位 CA2 加法哪个会溢出？", options: ["$+50 + (-30)$", "$+70 + (+60)$", "$-70 + (-60)$", "$+100 + (-100)$"], answer: 1, explain: "$130 > 127$；同号正+正变负 ⇒ 溢出。" },
{topic: "ca2", difficulty: 4, type: "fill", points: 3, q: "8 位 CA2 中 $35 + (-28)$ 结果（二进制）= ?", answer: "00000111", explain: "$35 + (-28) = 7$；异号永不溢；二进制 $0000\\,0111$。"},
{topic: "ca2", difficulty: 4, type: "mcq-multi", points: 3, q: "8 位 CA2 下列说法哪些正确？", options: ["范围 $[0, 255]$", "最小负数 $-128$", "最大正数 $127$", "存在两个零"], answer: [1, 2], explain: "范围 $[-128,127]$；只有一个 0。"},
{topic: "ca2", difficulty: 4, type: "fill", points: 3, q: "$-24$ 的 8 位 CA2 符号扩展到 16 位 = ?", answer: "1111111111101000", explain: "8 位 $-24 = 11101000$；扩展左侧补符号位 1。"},
{topic: "ca2", difficulty: 4, type: "judge", points: 2, q: "8 位 CA2 中 $-128$ 有对应的正数 $+128$。", answer: false, explain: "$+128 \\notin [-128, 127]$（CA2 不对称）。"},
{topic: "ca2", difficulty: 5, type: "subjective", points: 4, q: "为何 8 位 CA2 范围不对称？给 $k$ 位通用公式。", answer: "范围 $[-2^{k-1}, 2^{k-1}-1]$；$2^k$ 个值分正负，0 归非负 ⇒ 负数比正数多 1。", explain: "0 归正端导致负方向多一个值。"},
{topic: "ca2", difficulty: 5, type: "subjective", points: 4, q: "12 位 CA2 加法溢出检测器逻辑。", answer: "若两输入同号但输出异号 ⇒ 溢出；等价于最高两位进位异或 $C_{n-1} \\oplus C_n = 1$。", explain: "硬件常用最高两位进位异或检测，效率高。"},

{topic: "float", difficulty: 2, type: "mcq", points: 2, q: "IEEE 单精度（32 位）结构 = ?", options: ["1+8+23", "1+11+52", "1+7+24", "1+9+22"], answer: 0, explain: "符号 1 + 指数 8 + 尾数 23。"},
{topic: "float", difficulty: 2, type: "fill", points: 2, q: "IEEE 32 位浮点 bias = ?", answer: "127", explain: "$2^{8-1} - 1 = 127$。"},
{topic: "float", difficulty: 2, type: "mcq", points: 2, q: "IEEE 64 位浮点有效尾数（含隐含位）宽度 = ?", options: ["52 位", "53 位", "51 位", "64 位"], answer: 1, explain: "隐含 1 + 存储 52 = 53。"},
{topic: "float", difficulty: 3, type: "judge", points: 2, q: "IEEE 浮点中指数全 0、尾数全 0 表示 0。", answer: true, explain: "符号位 0 或 1 ⇒ $+0$ 或 $-0$。"},
{topic: "float", difficulty: 3, type: "mcq", points: 3, q: "IEEE 32 位编码哪个表示 NaN？", options: ["指数全 1、尾数全 0", "指数全 1、尾数非 0", "指数全 0、尾数非 0", "指数 128、尾数全 0"], answer: 1, explain: "指数全 1 + 尾数 0 = $\\pm\\infty$；指数全 1 + 尾数非 0 = NaN。"},
{topic: "float", difficulty: 3, type: "judge", points: 2, q: "IEEE 浮点非规约数（denormal）出现在指数全 0 且尾数非 0 时。", answer: true, explain: "用于平滑过渡到 0。"},
{topic: "float", difficulty: 3, type: "mcq-multi", points: 3, q: "IEEE 32 位 $00000000\\ldots$ 与 $10000000\\ldots$（其余全 0）分别表示？", options: ["第一个是 +0", "第二个是 −0", "都表示 0（值相等）", "是最大和最小"], answer: [0, 1, 2], explain: "$+0$ 与 $-0$ 在比较中相等。"},
{topic: "float", difficulty: 4, type: "fill", points: 3, q: "IEEE 32 位最小正规约数 ≈ $2^{?}$（填指数）", answer: "-126", explain: "$e_\\min = 1 - 127 = -126$。"},
{topic: "float", difficulty: 4, type: "mcq", points: 3, q: "IEEE 32 位浮点 overflow 时结果通常是？", options: ["舍入到最大", "$\\pm\\infty$", "NaN", "保持原值"], answer: 1, explain: "超出最大可表数 ⇒ $\\pm\\infty$。"},
{topic: "float", difficulty: 4, type: "judge", points: 2, q: "浮点加法满足结合律。", answer: false, explain: "因舍入误差非结合，例 $(10^{20}+1)-10^{20} \\neq 10^{20}+(1-10^{20})$。"},
{topic: "float", difficulty: 4, type: "fill", points: 3, q: "浮点中大数 + 小数（差超 ULP）时小数被吞没；$a+b$ ≈ ?（填变量）", answer: "a", explain: "对齐时小数尾数被截 ⇒ $a + b = a$。"},
{topic: "float", difficulty: 4, type: "subjective", points: 4, q: "解释 IEEE 浮点隐含位的作用。", answer: "规约数最高位恒为 1，不存储以省 1 bit；存储 23 位 + 隐含 1 = 24 位有效，精度提升 1 bit。", explain: "前提是规约数 $m \\in [1, 2)$。"},
{topic: "float", difficulty: 5, type: "mcq", points: 4, q: "下列哪个浮点计算会因舍入产生反直觉结果？", options: ["$0.1 + 0.2 = 0.3$", "$(a+b)+c = a+(b+c)$ 总成立", "$10^{20}+1-10^{20} = 0$", "正数累加 > 0"], answer: 2, explain: "$10^{20}$ 量级时 1 被吞没。"},
{topic: "float", difficulty: 5, type: "subjective", points: 4, q: "$0.1 \\times 10 \\times 100$ 与 $0.1 \\times 1000$ 哪个更精确？", answer: "前者更易累积误差；后者一次乘法误差更小。一般从大量级到小量级或反之要规划顺序。", explain: "浮点乘法非可交换性导致中间结果舍入差异。"},
{topic: "float", difficulty: 5, type: "fill", points: 4, q: "IEEE 32 位机器精度 $\\varepsilon_\\text{mach} = 2^{?}$", answer: "-23", explain: "尾数 23 位 ⇒ $\\varepsilon = 2^{-23} \\approx 1.19\\times 10^{-7}$。"},

/* === 段 B：布尔 / Karnaugh / Beth === */
{topic: "boolean", difficulty: 3, type: "fill", points: 3, q: "化简 $a(a+b) + b(a+b)$。", answer: "a+b", explain: "$(a+b)(a+b) = a+b$（幂等律）。"},
{topic: "boolean", difficulty: 2, type: "judge", points: 2, q: "$\\overline{ab+c} = \\overline a + \\overline b \\cdot \\overline c$", answer: false, explain: "正确为 $\\overline{ab+c} = (\\overline a + \\overline b)\\cdot \\overline c$。"},
{topic: "boolean", difficulty: 3, type: "fill", points: 3, q: "$(a + \\overline b)(\\overline a + c)(b + \\overline c)$ 真值表中为真的行数 = ?", answer: "2", explain: "枚举 8 行真值表得 2 个为真组合。"},
{topic: "boolean", difficulty: 4, type: "mcq", points: 3, q: "化简 $ab + \\overline a b + \\overline a \\overline b$ = ?", options: ["$\\overline a$", "$a+b$", "$\\overline a + b$", "$\\overline{ab}$"], answer: 2, explain: "$= b + \\overline a \\overline b = b + \\overline a$。"},
{topic: "boolean", difficulty: 3, type: "fill", points: 2, q: "$\\overline{\\overline a + b}\\cdot c$ 化简（无嵌套否定）= ?", answer: "a b̄ c", explain: "De Morgan：$\\overline{\\overline a + b} = a\\overline b$。"},
{topic: "boolean", difficulty: 2, type: "mcq", points: 2, q: "下列哪个**不是**重言式？", options: ["$a + \\overline a$", "$ab + \\overline a + \\overline b$", "$a \\to (a + b)$", "$\\overline{(ab)\\to(a+b)}$"], answer: 3, explain: "$ab \\to a+b$ 恒真 ⇒ 其否定恒假，不是重言式。"},
{topic: "boolean", difficulty: 4, type: "fill", points: 3, q: "$(a + \\overline b)(\\overline a + b)$ 的 minterm（写成 $m_i$ 求和形式）= ?", answer: "m0 + m3", explain: "真值表中 $f=1$：$(a,b)=(0,0)$ 即 $m_0$，$(1,1)$ 即 $m_3$。"},
{topic: "boolean", difficulty: 3, type: "mcq-multi", points: 3, q: "下列哪些操作保持布尔等价？", options: ["对所有变量同时取否", "用 De Morgan 展开否定", "$a\\to b$ 替换为 $\\overline a + b$", "交换合取项顺序"], answer: [1, 2, 3], explain: "对所有变量同时取否一般**不**保持等价（除非函数自对偶）。"},
{topic: "boolean", difficulty: 5, type: "subjective", points: 4, q: "给 $f = \\overline a bc + a\\overline b c + abc$，求 FND 与 FNC。", answer: "FND = $\\overline a bc + a\\overline b c + abc$；FNC 可从 $f=0$ 行构造。", explain: "FND 直接读 1 行；FNC 读 0 行（每项对值取反）。"},
{topic: "boolean", difficulty: 2, type: "judge", points: 2, q: "$a + a = a$ 和 $a + 0 = a$ 是布尔代数公理。", answer: true, explain: "幂等律 + 单位元。"},
{topic: "boolean", difficulty: 3, type: "fill", points: 3, q: "化简 $\\overline a\\overline b\\overline c + \\overline a\\overline bc + \\overline a bc + abc$ = ?", answer: "ā b̄ + bc", explain: "$\\overline a\\overline b(\\overline c + c) + bc(\\overline a + a) = \\overline a\\overline b + bc$。"},
{topic: "boolean", difficulty: 4, type: "mcq", points: 3, q: "$F = (a\\to b)\\land(b\\to c)\\land\\neg c$ 为真的赋值有几个？", options: ["0", "1", "2", "3"], answer: 1, explain: "$\\neg c\\Rightarrow c=0$；$b\\to c\\Rightarrow b=0$；$a\\to b\\Rightarrow a=0$。唯一解 $(0,0,0)$。"},
{topic: "boolean", difficulty: 3, type: "fill", points: 2, q: "对 $E = a(\\overline b + c)$ 应用分配律 = ?", answer: "a b̄ + ac", explain: "标准分配律。"},
{topic: "boolean", difficulty: 2, type: "mcq", points: 2, q: "下列哪个恒等式**错误**？", options: ["$a + ab = a$", "$aa = a$", "$a+b = \\overline{\\overline a\\overline b}$", "$a\\to b = a + b$"], answer: 3, explain: "$a\\to b \\equiv \\overline a + b$，不是 $a+b$。"},
{topic: "boolean", difficulty: 4, type: "fill", points: 3, q: "$f = 0$ 在 $(0,0,0),(0,1,0),(1,0,0)$；其 FNC 最简（化简后）= ?", answer: "(a+c)(b̄+c)", explain: "公共特征 $c=0$ 部分约束，结合最简。"},
{topic: "boolean", difficulty: 3, type: "judge", points: 2, q: "$\\overline{(ab)\\lor(cd)} = (\\overline a\\lor\\overline b)\\land(\\overline c\\lor\\overline d)$", answer: true, explain: "外层 De Morgan + 内层各自展开。"},

{topic: "karnaugh", difficulty: 2, type: "fill", points: 2, q: "4 变量 K-map 行（ab）按格雷码：00, ?, 11, 10。问号 = ?", answer: "01", explain: "格雷码序列。"},
{topic: "karnaugh", difficulty: 3, type: "mcq", points: 3, q: "K-map 分组规则下列哪个**错**？", options: ["分组必须为矩形", "分组大小必须 $2^k$", "同一个 1 可在多分组", "对角格可在同分组"], answer: 3, explain: "K-map 仅按边相邻；对角不能直接相圈。"},
{topic: "karnaugh", difficulty: 4, type: "mcq", points: 3, q: "4 变量 K-map 单项最大有效圈 = ?", options: ["4", "8", "16", "取决于函数"], answer: 1, explain: "16 = 常 1；最大单 littéral 圈 = 8 = $2^3$。"},
{topic: "karnaugh", difficulty: 3, type: "fill", points: 2, q: "5 变量 K-map 通常画为两张 4 变量表，跨页相邻指 = ?", answer: "两表对应位置", explain: "$e=0$ 与 $e=1$ 同位置视为相邻。"},
{topic: "karnaugh", difficulty: 2, type: "judge", points: 2, q: "K-map 中 don't-care 圈入分组后，最终公式对该位置输出确定。", answer: true, explain: "化简后表达式确定，don't-care 仅化简过程灵活。"},
{topic: "karnaugh", difficulty: 3, type: "mcq-multi", points: 3, q: "K-map 中 don't-care 用法正确的有？", options: ["可视为 1 扩大圈", "可视为 0 避免某项", "× 必须被覆盖", "× 可不全覆盖"], answer: [0, 1, 3], explain: "× 不强制覆盖，仅 1 必须覆盖。"},
{topic: "karnaugh", difficulty: 3, type: "judge", points: 2, q: "FNC 在 K-map 中通过圈 0 读出，每项是析取。", answer: true, explain: "FNC 外层合取，内层析取。"},
{topic: "karnaugh", difficulty: 2, type: "judge", points: 2, q: "3 变量 K-map 中 $(a,b,c)=(0,1,1)$ 编号为 $m_3$。", answer: true, explain: "二进制 011 = 3。"},
{topic: "karnaugh", difficulty: 3, type: "mcq", points: 3, q: "4 变量 K-map 四角格子之间相邻关系？", options: ["完全不相邻", "两两相邻", "仅上下或左右", "四角构成一个连通分组"], answer: 3, explain: "环面拓扑使四角相邻。"},
{topic: "karnaugh", difficulty: 4, type: "fill", points: 3, q: "5 变量 K-map 跨两页的最大矩形分组 = ?（格子数）", answer: "16", explain: "每页最多 8（共 16 格中半数），跨页合并最多 16。"},
{topic: "karnaugh", difficulty: 3, type: "fill", points: 2, q: "K-map 用格雷码的主要优势 = ?", answer: "保证相邻格仅 1 位差异", explain: "便于直观找最大矩形。"},

{topic: "beth", difficulty: 2, type: "judge", points: 2, q: "Beth 树中 α 规则不分叉，β 规则分叉。", answer: true, explain: "α: ∧, ¬∨, ¬→；β: ∨, →, ↔, ¬∧。"},
{topic: "beth", difficulty: 3, type: "fill", points: 2, q: "对 $\\neg(a\\land b)$ Beth 树用何规则？分支 = ?", answer: "β; ¬a | ¬b", explain: "$\\neg(\\land)$ 是 β 规则。"},
{topic: "beth", difficulty: 4, type: "judge", points: 3, q: "若 $\\Sigma\\cup\\{\\neg F\\}$ 的 Beth 树全闭，则 $\\Sigma \\models F$。", answer: true, explain: "无反模型 ⇒ 蕴含成立。"},
{topic: "beth", difficulty: 3, type: "judge", points: 2, q: "Beth 树支闭合 ⇔ 出现 $p$ 与 $\\neg p$ 矛盾。", answer: true, explain: "矛盾字面量定义。"},
{topic: "beth", difficulty: 3, type: "mcq", points: 3, q: "$a \\to (b \\lor c)$ 的 Beth 树第一步分支 = ?", options: ["$\\neg a$ 单支", "$b\\lor c$ 单支", "$\\neg a$ | $(b\\lor c)$", "$a \\land \\neg(b\\lor c)$"], answer: 2, explain: "$\\to$ 是 β 规则。"},
{topic: "beth", difficulty: 2, type: "fill", points: 2, q: "Beth 树中含 $p$ 与 $\\neg p$ 的支称 = ?", answer: "闭支", explain: "Closed branch / closed."},
{topic: "beth", difficulty: 4, type: "mcq-multi", points: 3, q: "$F$ 是重言式 ⇔ 下列哪些等价？", options: ["真值表全 1", "$\\{\\neg F\\}$ 的 Beth 树全闭", "所有赋值满足", "$\\models F$"], answer: [0, 1, 2, 3], explain: "都是等价刻画。"},
{topic: "beth", difficulty: 3, type: "fill", points: 3, q: "证 $\\{p, p\\to q\\}\\models q$：加 $\\neg q$，β 拆 $p\\to q$ 得 = ?", answer: "¬p | q", explain: "两支均闭：$\\neg p$ 与 $p$，$q$ 与 $\\neg q$。"},
{topic: "beth", difficulty: 4, type: "judge", points: 2, q: "Beth 树中遇 $\\neg\\neg a$ 应用双否消除得 $a$（α 规则）。", answer: true, explain: "$\\neg\\neg$ 化简为原子。"},
{topic: "beth", difficulty: 3, type: "fill", points: 2, q: "$\\neg(a\\leftrightarrow b)$ 是何类型？分支 = ?", answer: "β; (a∧¬b) | (¬a∧b)", explain: "等价的否定 = 异或。"},
{topic: "beth", difficulty: 5, type: "subjective", points: 4, q: "用 Beth 验证 $\\{a\\lor b, \\neg a\\to c\\} \\models b\\lor c$。", answer: "假设 $\\neg b, \\neg c$；β $a\\lor b$：$a$ 支由 $\\neg a\\to c$ + $\\neg c$ 推 $a$ 矛盾；$b$ 支与 $\\neg b$ 矛盾。全闭。", explain: "经典分情况推理。"},
{topic: "beth", difficulty: 4, type: "mcq", points: 3, q: "Beth 树某支已闭后，应：", options: ["继续穷尽展开", "停止该支", "分裂新支", "交语义"], answer: 1, explain: "闭支即矛盾，无需展开。"},
{topic: "beth", difficulty: 2, type: "fill", points: 2, q: "α 规则代表形式有 $a\\land b$ 和 = ?", answer: "¬(a∨b) 或 ¬(a→b)", explain: "α: ∧, ¬∨, ¬→, ¬¬。"},
{topic: "beth", difficulty: 2, type: "mcq", points: 2, q: "$\\neg(p\\to q)$ 展开后字面量 = ?", options: ["$\\neg p, \\neg q$", "$p, \\neg q$", "$\\neg p, q$", "$p, q$"], answer: 1, explain: "$\\neg(p\\to q) = p \\land \\neg q$。"},
{topic: "boolean", difficulty: 4, type: "mcq", points: 3, q: "$f = ab + \\overline a\\overline c + bc$ 化简后**不**等价的是？", options: ["$ab + \\overline a\\overline c$", "$b + \\overline a\\overline c$", "$ab + \\overline c$", "$\\overline a\\overline c + bc$"], answer: 2, explain: "$ab + \\overline c$ 缺少 $bc$ 在 $a=1, b=0, c=0$ 时的覆盖。"},
{topic: "boolean", difficulty: 2, type: "fill", points: 2, q: "$a + \\overline a b = a + b$ 称 = ?", answer: "吸收律", explain: "Absorption。"},
{topic: "beth", difficulty: 3, type: "fill", points: 3, q: "证 $\\vdash (a\\to b)\\lor(b\\to a)$ Beth 树第一步 = ?", answer: "对 ¬F 应用 ¬∨（α）展开为 ¬(a→b) 与 ¬(b→a)", explain: "都得 $a, \\neg b$ 与 $b, \\neg a$ 同时存在 ⇒ 矛盾。"},
{topic: "boolean", difficulty: 2, type: "mcq", points: 2, q: "布尔代数中 0 和 1 分别表示？", options: ["真 假", "假 真", "空 全", "否 是"], answer: 1, explain: "$1 = T$, $0 = F$。"},
{topic: "boolean", difficulty: 5, type: "subjective", points: 4, q: "证 De Morgan 律对 3 个变量：$\\overline{abc} = \\overline a + \\overline b + \\overline c$。", answer: "$\\overline{abc} = \\overline{(ab)c} = \\overline{ab} + \\overline c = \\overline a + \\overline b + \\overline c$（递归用 2 元 De Morgan）。", explain: "n 元归纳。"},
{topic: "karnaugh", difficulty: 4, type: "fill", points: 3, q: "5 变量 K-map 中两页对应位置 4 元矩形分组合并后消去的变量 = ?", answer: "e", explain: "$e=0$ 与 $e=1$ 都覆盖 ⇒ 消去 $e$。"},
{topic: "boolean", difficulty: 3, type: "judge", points: 2, q: "$\\overline{a+b}\\cdot c = \\overline a c + \\overline b c$。", answer: false, explain: "$\\overline{a+b}\\cdot c = \\overline a\\overline b c$，不是和。"},
{topic: "beth", difficulty: 4, type: "mcq", points: 3, q: "$\\Sigma=\\{a\\to b, \\neg b\\}$ 验证 $\\models \\neg a$ 的 Beth 树关键步骤？", options: ["$\\neg a, \\neg b, a$ 三字面", "$b, \\neg a, \\neg b$ 三字面", "β 拆 $a\\to b$ 两支自闭", "$a, b$ 待分析"], answer: 2, explain: "$\\neg a$ 支与 $a$ 矛盾；$b$ 支与 $\\neg b$ 矛盾。"},

/* === 段 B2：方法诊断补强（减少纯计算感） === */
{topic: "boolean", difficulty: 3, type: "mcq", points: 3, q: "化简布尔式时，哪一步最适合先做？$F=a b+a\\overline b$", options: ["提取公共因子 $a$", "直接画 4 变量 K-map", "把 $a$ 取反", "枚举 16 行"], answer: 0, explain: "$ab+a\\overline b=a(b+\\overline b)=a$；这题考方法选择。"},
{topic: "boolean", difficulty: 3, type: "mcq", points: 3, q: "学生把 $a+bc$ 化成 $(a+b)c$。正确诊断是？", options: ["正确", "错，应为 $(a+b)(a+c)$", "错，应为 $ab+ac$", "错，应为 $abc$"], answer: 1, explain: "布尔代数中 $a+bc=(a+b)(a+c)$，不能把 $c$ 强行提出。"},
{topic: "boolean", difficulty: 3, type: "judge", points: 2, q: "判断 $F$ 是否为重言式时，只找到一个反例就足够否定。", answer: true, explain: "重言式要求所有赋值为真；一个反例即可说明不是重言式。"},
{topic: "boolean", difficulty: 4, type: "mcq", points: 3, q: "从真值表构造 FND 时，应读取哪些行？", options: ["$F=1$ 的行", "$F=0$ 的行", "变量全为 0 的行", "任意两行"], answer: 0, explain: "FND 是析取范式，直接由使函数为真的 minterm 构成。"},
{topic: "boolean", difficulty: 4, type: "mcq", points: 3, q: "从真值表构造 FNC 时，应读取哪些行？", options: ["$F=1$ 的行", "$F=0$ 的行", "只读第一行", "只读 don't-care"], answer: 1, explain: "FNC 是合取范式，读取 $F=0$ 的行并写成 maxterm。"},
{topic: "boolean", difficulty: 3, type: "mcq-multi", points: 3, q: "化简 $ab+a\\overline b+\\overline a b$ 时，哪些思路有效？", options: ["提取 $a$ 得 $a(b+\\overline b)$", "用 K-map 圈三个 1", "把它误写成 $abc$", "识别最终等价于 $a+b$"], answer: [0, 1, 3], explain: "$ab+a\\overline b=a$，再 $a+\\overline a b=a+b$。"},

{topic: "karnaugh", difficulty: 3, type: "mcq", points: 3, q: "K-map 中圈选的优先目标是什么？", options: ["尽量圈最大且合法的 $2^k$ 矩形", "每个 1 单独成圈", "只圈对角线", "只圈第一行"], answer: 0, explain: "最大合法圈能消去最多变量，使表达式更简。"},
{topic: "karnaugh", difficulty: 3, type: "judge", points: 2, q: "K-map 中同一个 1 可以被多个分组覆盖。", answer: true, explain: "重复覆盖允许，常用于得到更大的圈或覆盖必要项。"},
{topic: "karnaugh", difficulty: 3, type: "mcq", points: 3, q: "K-map 中圈 1 得到的通常是哪种形式？", options: ["FND / 和项之和", "FNC / 积项之积", "二进制补码", "RSA 私钥"], answer: 0, explain: "圈 1 读出积项，再把积项相加，即 FND 思路。"},
{topic: "karnaugh", difficulty: 3, type: "mcq", points: 3, q: "K-map 中圈 0 得到的通常是哪种形式？", options: ["FNC", "FND", "补码", "校验码"], answer: 0, explain: "圈 0 读出和项，最后合取，得到 FNC。"},
{topic: "karnaugh", difficulty: 4, type: "judge", points: 2, q: "4 变量 K-map 的左右边界可以相邻。", answer: true, explain: "K-map 具有环绕相邻性，边界可跨边合并。"},
{topic: "karnaugh", difficulty: 4, type: "mcq", points: 3, q: "若 4 变量 K-map 中四个角都是 1，最合理的处理是？", options: ["四角可合成一个 4 格圈", "四角必须分开", "四角是对角所以全不能圈", "只能圈左上角"], answer: 0, explain: "四角通过上下和左右环绕相邻，构成合法 4 格圈。"},
{topic: "karnaugh", difficulty: 4, type: "mcq-multi", points: 3, q: "关于 don't-care 的使用，哪些正确？", options: ["可以当 1 用来扩大圈", "可以当 0 不圈", "必须全部圈入", "不能覆盖真正的 0"], answer: [0, 1, 3], explain: "don't-care 服务于化简；是否圈入取决于能否得到更大合法圈。"},
{topic: "karnaugh", difficulty: 3, type: "judge", points: 2, q: "K-map 分组大小必须是 $1,2,4,8,\\ldots$。", answer: true, explain: "分组大小必须是 $2^k$，并且形状是合法矩形。"},

{topic: "rsa", difficulty: 3, type: "mcq", points: 3, q: "RSA 中若只给 $n=77$ 和 $e=13$，还缺少哪项才能直接求私钥 $d$？", options: ["$\\varphi(n)$ 或 $p,q$", "密文长度", "K-map 分组", "浮点 bias"], answer: 0, explain: "求 $d$ 需要在模 $\\varphi(n)$ 下取 $e$ 的逆元；不知道 $p,q$ 通常就不知道 $\\varphi(n)$。"},
{topic: "rsa", difficulty: 4, type: "mcq", points: 3, q: "RSA 例题中 $p=7,q=11,e=13$。为什么 $e$ 合法？", options: ["$13$ 与 $\\varphi=60$ 互素", "$13>n$", "$13$ 是奇数即可", "$13$ 等于 $p+q$"], answer: 0, explain: "$\\varphi=(7-1)(11-1)=60$，$\\gcd(13,60)=1$。"},
{topic: "rsa", difficulty: 3, type: "mcq", points: 3, q: "RSA 加密后得到密文 $c$，接收者用什么信息解密？", options: ["私钥指数 $d$ 和模数 $n$", "只用公钥 $e$", "只用 $p+q$", "只用明文 $m$"], answer: 0, explain: "解密公式是 $m\\equiv c^d\\pmod n$。"},
{topic: "rsa", difficulty: 4, type: "judge", points: 2, q: "若 $m$ 与 $n$ 不互素，课堂小例子中仍应先检查 RSA 参数流程，而不是把问题改成普通模幂题。", answer: true, explain: "考试重点通常是 RSA 参数、模数和逆元条件；不要把应用题降格成孤立大数计算。"},
{topic: "rsa", difficulty: 3, type: "mcq-multi", points: 3, q: "RSA 小例子里哪些量通常需要保密？", options: ["$p$", "$q$", "$d$", "$e$"], answer: [0, 1, 2], explain: "$e$ 属于公钥可公开；$p,q,d$ 泄露会破坏安全。"},

/* === 段 C：模运算 / RSA / 校验码（偏方法与应用） === */
{topic: "modular", difficulty: 2, type: "mcq", points: 2, q: "$\\mathbb Z_{11}$ 中 $7 + 5 = ?$", options: ["12", "1", "0", "11"], answer: 1, explain: "$12 \\equiv 1 \\pmod{11}$。这是保留的少量基础计算，用来确认同余代表元。"},
{topic: "modular", difficulty: 2, type: "judge", points: 2, q: "若 $p$ 素数，$\\mathbb Z_p$ 中每个非零元都有乘法逆元。", answer: true, explain: "$1\\le k\\le p-1$ 时 $\\gcd(k,p)=1$，因此存在 $k^{-1}$。"},
{topic: "modular", difficulty: 3, type: "mcq-multi", points: 3, q: "在 $\\mathbb Z_{12}$ 中，哪些元素有乘法逆元？", options: ["1", "5", "6", "7", "11"], answer: [0, 1, 3, 4], explain: "可逆当且仅当与 12 互素；$1,5,7,11$ 可逆，6 不可逆。"},
{topic: "modular", difficulty: 3, type: "mcq", points: 3, q: "在 $\\mathbb Z_{12}$ 中，方程 $4x\\equiv 8\\pmod{12}$ 有几个解？", options: ["0", "1", "3", "4"], answer: 3, explain: "$\\gcd(4,12)=4$ 且 $4|8$，所以有 4 个解；约简得 $x\\equiv2\\pmod3$，即 $\\{2,5,8,11\\}$。"},
{topic: "modular", difficulty: 3, type: "mcq-multi", points: 3, q: "下列哪些同余方程可以直接乘以系数的逆元来求解？", options: ["$5x\\equiv7\\pmod{12}$", "$4x\\equiv8\\pmod{12}$", "$7x\\equiv3\\pmod{12}$", "$6x\\equiv1\\pmod{12}$"], answer: [0, 2], explain: "只有系数与模数互素时才可直接除以系数；5 与 7 在 $\\mathbb Z_{12}$ 中可逆。"},
{topic: "modular", difficulty: 2, type: "judge", points: 2, q: "由 $2a\\equiv2b\\pmod6$ 可以直接推出 $a\\equiv b\\pmod6$。", answer: false, explain: "2 在 $\\mathbb Z_6$ 中不可逆，不能直接约掉。反例：$a=1,b=4$。"},
{topic: "modular", difficulty: 3, type: "judge", points: 2, q: "$\\mathbb Z_6$ 中 $3x\\equiv 3\\pmod6$ 有唯一解。", answer: false, explain: "$\\gcd(3,6)=3$ 且 $3|3$，所以有 3 个解：$\\{1,3,5\\}$。"},
{topic: "modular", difficulty: 3, type: "mcq", points: 3, q: "下列哪一步错误使用了费马小定理？", options: ["$2^{10}\\equiv1\\pmod{11}$", "$3^6\\equiv1\\pmod7$", "$2^4\\equiv1\\pmod{15}$", "$5^{12}\\equiv1\\pmod{13}$"], answer: 2, explain: "费马小定理要求模数是素数；15 不是素数，不能直接套用。"},
{topic: "modular", difficulty: 3, type: "mcq", points: 3, q: "在 $\\mathbb Z_{15}$ 中，为什么不能把 $3x\\equiv6$ 两边同时除以 3 得 $x\\equiv2$？", options: ["3 在 $\\mathbb Z_{15}$ 中不可逆", "6 不是偶数", "15 是奇数", "同余式不能加减"], answer: 0, explain: "$\\gcd(3,15)=3$，3 没有乘法逆元。原方程有多个解，直接除法会丢解。"},
{topic: "modular", difficulty: 2, type: "fill", points: 2, q: "$9^{-1} \\bmod 26 = ?$", answer: "3", explain: "$1=3\\cdot9-26$，所以 $9^{-1}\\equiv3\\pmod{26}$。这类小扩欧是 RSA 求 $d$ 的准备。"},
{topic: "modular", difficulty: 3, type: "fill", points: 2, q: "$\\mathbb Z_{10}$ 中所有可逆元集合是？", answer: "{1,3,7,9}", explain: "可逆元正是与 10 互素的剩余类。"},
{topic: "modular", difficulty: 3, type: "judge", points: 2, q: "$\\mathbb Z_{15}$ 是整环。", answer: false, explain: "$3\\cdot5\\equiv0\\pmod{15}$，但 3 和 5 都不是 0；存在零因子。课件只需掌握这个边界，不需深入环论。"},
{topic: "modular", difficulty: 3, type: "mcq", points: 3, q: "若 $n=pq$ 且 $p,q$ 是不同素数，$\\varphi(n)$ 应怎样算？", options: ["$n-1$", "$(p-1)(q-1)$", "$p+q$", "$pq-p$"], answer: 1, explain: "RSA 中使用 $\\varphi(pq)=(p-1)(q-1)$。"},
{topic: "modular", difficulty: 3, type: "mcq-multi", points: 3, q: "关于 $\\mathbb Z_n$ 中的逆元，下列哪些说法正确？", options: ["加法逆元总存在", "乘法逆元总存在", "乘法逆元存在当且仅当 $\\gcd(x,n)=1$", "$n$ 为素数时非零元都有乘法逆元"], answer: [0, 2, 3], explain: "加法逆元与乘法逆元条件不同，这是同余方程与 RSA 的核心边界。"},
{topic: "modular", difficulty: 3, type: "mcq", points: 3, q: "用模 7 校验码 $c(s)=7-(s\\bmod7)$ 时，校验的核心目的是什么？", options: ["压缩信息", "检测录入错误", "加密明文", "把十进制转二进制"], answer: 1, explain: "校验码不是加密；它用同余性质检测某些传输或录入错误。"},
{topic: "modular", difficulty: 4, type: "judge", points: 3, q: "若校验模数为 11，十进制数码的一位错误一定会改变校验值。", answer: true, explain: "一位错误差量为 $\\Delta=(d'-d)10^i$；$|d'-d|<11$ 且 $\\gcd(10,11)=1$，所以 $\\Delta\\not\\equiv0\\pmod{11}$。"},
{topic: "modular", difficulty: 3, type: "mcq", points: 3, q: "若把校验模数改成 6，哪种一位错误可能漏检？", options: ["个位 0 改 6", "个位 0 改 1", "十位 0 改 1", "百位 2 改 3"], answer: 0, explain: "个位差量 6 在模 6 下为 0，校验值可能不变。"},
{topic: "modular", difficulty: 4, type: "mcq-multi", points: 3, q: "十进制一位错校验选择模数 $p$ 时，哪些条件有助于证明可检出一位错误？", options: ["$p>9$", "$\\gcd(10,p)=1$", "$p$ 必须小于 10", "$10$ 在模 $p$ 下不可逆"], answer: [0, 1], explain: "数字差绝对值最多 9；同时 $10^i$ 需要可逆，才能保证非零差量不会消失。"},

{topic: "rsa", difficulty: 3, type: "mcq", points: 3, q: "RSA 密钥生成的正确顺序是？", options: ["选 $e$ → 选 $p,q$ → 算 $d$ → 算 $n$", "选 $p,q$ → 算 $n,\\varphi(n)$ → 选与 $\\varphi$ 互素的 $e$ → 求 $d$", "选 $n$ → 任取 $e,d$", "先加密明文再决定私钥"], answer: 1, explain: "RSA 的流程是先得到 $n$ 和 $\\varphi(n)$，再选择合法 $e$，最后求 $d=e^{-1}\\pmod{\\varphi(n)}$。"},
{topic: "rsa", difficulty: 3, type: "mcq-multi", points: 3, q: "若 $\\varphi(n)=40$，下列哪些 $e$ 可作为 RSA 公钥指数？", options: ["3", "10", "20", "37"], answer: [0, 3], explain: "需要 $1<e<\\varphi(n)$ 且 $\\gcd(e,40)=1$；3 和 37 合法。"},
{topic: "rsa", difficulty: 2, type: "judge", points: 2, q: "RSA 私钥 $d$ 满足 $ed\\equiv1\\pmod n$。", answer: false, explain: "模数应是 $\\varphi(n)$，不是 $n$。这是高频陷阱。"},
{topic: "rsa", difficulty: 3, type: "mcq", points: 3, q: "RSA 中 $p=5,q=11,e=3$。下列哪个是正确的 $d$？", options: ["3", "13", "27", "40"], answer: 2, explain: "$\\varphi=4\\cdot10=40$，$3\\cdot27=81\\equiv1\\pmod{40}$。"},
{topic: "rsa", difficulty: 3, type: "fill", points: 2, q: "RSA $p=5,q=11,e=3,m=4$，密文 $c=m^e\\bmod n$ 等于？", answer: "9", explain: "$n=55$，$4^3=64\\equiv9\\pmod{55}$。"},
{topic: "rsa", difficulty: 4, type: "mcq", points: 3, q: "学生说 $p=7,q=13,e=5$ 时 $d$ 是 $5^{-1}\\bmod91$。错在哪里？", options: ["$n$ 算错", "$e$ 不能为 5", "$d$ 应模 $\\varphi(n)=72$，且 $d=29$", "$d$ 应等于 $\\varphi(n)$"], answer: 2, explain: "$n=91$，但求私钥指数要模 $\\varphi=6\\cdot12=72$；$5\\cdot29=145\\equiv1\\pmod{72}$。"},
{topic: "rsa", difficulty: 3, type: "mcq-multi", points: 3, q: "关于 RSA 公钥/私钥，下列哪些正确？", options: ["公钥常写 $(n,e)$", "私钥可写 $(n,d)$", "$e$ 可公开", "$p,q$ 应公开"], answer: [0, 1, 2], explain: "$p,q$ 泄露后可算 $\\varphi(n)$，进而恢复私钥 $d$。"},
{topic: "rsa", difficulty: 3, type: "judge", points: 2, q: "若攻击者知道 $n=pq$ 与 $\\varphi(n)$，就能恢复 $p,q$。", answer: true, explain: "$p+q=n-\\varphi(n)+1$ 且 $pq=n$，可解二次方程恢复两个素因子。"},
{topic: "rsa", difficulty: 2, type: "mcq", points: 2, q: "RSA 安全性主要依赖什么困难问题？", options: ["大整数 $n$ 难以分解成 $p,q$", "十进制转换困难", "Karnaugh 分组困难", "加法很慢"], answer: 0, explain: "知道 $p,q$ 就能得到 $\\varphi(n)$ 和 $d$；难点是从大 $n$ 分解出 $p,q$。"},
{topic: "rsa", difficulty: 3, type: "mcq", points: 3, q: "给定公钥 $(n,e)=(33,3)$，明文 $m=5$。加密公式应写成？", options: ["$c\\equiv 5^3\\pmod{33}$", "$c\\equiv 3^5\\pmod{33}$", "$c\\equiv 5^{33}\\pmod3$", "$c\\equiv 33^3\\pmod5$"], answer: 0, explain: "RSA 加密是 $c=m^e\\bmod n$。"},
{topic: "rsa", difficulty: 4, type: "subjective", points: 4, q: "解释为什么 RSA 中 $d$ 要满足 $ed\\equiv1\\pmod{\\varphi(n)}$。", answer: "因为 $ed=1+k\\varphi(n)$，解密时 $c^d=(m^e)^d=m^{1+k\\varphi(n)}\\equiv m$，核心用到欧拉定理。", explain: "重点是说明指数回到 $1$，而不是机械求一个逆元。"},
{topic: "rsa", difficulty: 3, type: "mcq", points: 3, q: "RSA 中选择 $e$ 时，下列哪一项最关键？", options: ["$e$ 必须是偶数", "$e$ 必须与 $\\varphi(n)$ 互素", "$e$ 必须等于 $p$", "$e$ 必须大于 $n$"], answer: 1, explain: "只有 $\\gcd(e,\\varphi(n))=1$，$e$ 才有模 $\\varphi(n)$ 的逆元 $d$。"},
{topic: "rsa", difficulty: 3, type: "judge", points: 2, q: "只要 $e$ 与 $n$ 互素，就一定能作为 RSA 的公钥指数。", answer: false, explain: "条件应是 $\\gcd(e,\\varphi(n))=1$，不是与 $n$ 互素。"},
{topic: "rsa", difficulty: 3, type: "mcq", points: 3, q: "若 $p=3,q=11$，为什么 $e=5$ 不合法？", options: ["$n=33$ 太小", "$5$ 与 $\\varphi(n)=20$ 不互素", "$5$ 不是素数", "$5$ 不能公开"], answer: 1, explain: "$\\varphi=20$，$\\gcd(5,20)=5$，所以不存在 $d=5^{-1}\\pmod{20}$。"},
{topic: "rsa", difficulty: 3, type: "fill", points: 2, q: "RSA $p=7,q=11$ 时 $n$ 等于？", answer: "77", explain: "$n=pq=77$。这一步简单，但后续的 $\\varphi,e,d$ 都依赖它。"},
{topic: "rsa", difficulty: 3, type: "fill", points: 2, q: "RSA $p=7,q=11$ 时 $\\varphi(n)$ 等于？", answer: "60", explain: "$\\varphi(n)=(7-1)(11-1)=60$。"},
{topic: "rsa", difficulty: 3, type: "mcq", points: 3, q: "RSA $p=7,q=11,\\varphi=60$，哪个 $e$ 合法？", options: ["6", "10", "13", "15"], answer: 2, explain: "只有 $\\gcd(13,60)=1$。"},
{topic: "rsa", difficulty: 4, type: "mcq", points: 3, q: "若 $n=55$ 且 $\\varphi(n)=40$，则 $p+q$ 等于？", options: ["14", "16", "40", "55"], answer: 1, explain: "$\\varphi=pq-p-q+1=n-(p+q)+1$，所以 $p+q=55-40+1=16$。"},
{topic: "rsa", difficulty: 4, type: "subjective", points: 4, q: "给出 RSA 小例子的完整检查清单：从 $p,q$ 到加密，必须依次检查哪些对象？", answer: "检查 $p,q$ 为素数；算 $n=pq$；算 $\\varphi=(p-1)(q-1)$；选 $e$ 且 $\\gcd(e,\\varphi)=1$；求 $d=e^{-1}\\bmod\\varphi$；用 $c=m^e\\bmod n$ 加密。", explain: "这题考方法流程，不考大数计算。"},
{topic: "rsa", difficulty: 4, type: "mcq-multi", points: 3, q: "下列哪些信息泄露会明显削弱 RSA？", options: ["$p,q$", "$\\varphi(n)$", "私钥指数 $d$", "公钥指数 $e$"], answer: [0, 1, 2], explain: "$e$ 本来公开；$p,q,\\varphi,d$ 任一类核心秘密泄露都会使解密可行。"},
{topic: "rsa", difficulty: 4, type: "mcq", points: 3, q: "同学把 RSA 解密写成 $m\\equiv c^e\\pmod n$。问题是？", options: ["解密应使用 $d$ 而非 $e$", "不能取模", "应模 $\\varphi(n)$", "明文不能是数字"], answer: 0, explain: "加密用公钥指数 $e$，解密用私钥指数 $d$：$m\\equiv c^d\\pmod n$。"},
{topic: "rsa", difficulty: 3, type: "judge", points: 2, q: "RSA 的加密和解密都发生在 $\\mathbb Z_n$ 中。", answer: true, explain: "明文、密文都按模 $n$ 的剩余类处理。"},
{topic: "rsa", difficulty: 4, type: "subjective", points: 4, q: "为什么课堂上的 RSA 例子通常选很小的 $p,q$，而真实应用不能这样做？", answer: "小数便于手算流程；真实应用若 $n$ 太小会被快速分解，从而算出 $\\varphi$ 和 $d$。", explain: "重点是区分教学例子和安全参数。"}

];

if (typeof module !== "undefined") module.exports = NEWPOOL;
