/* 原始题池 — 由 3 个子 agent 生成，~150 道新题。
   build.js 会做类型校验后混合到 quizzes.js。 */

const NEWPOOL = [

/* === 段 A：进制 / CA2 / 浮点 === */
{topic: "base", difficulty: 2, type: "fill", points: 2, q: "将十进制数 $(47)_{10}$ 转换为二进制（不含括号）。", answer: "101111", explain: "47÷2 余 1, 23÷2 余 1, 11÷2 余 1, 5÷2 余 1, 2÷2 余 0, 1÷2 余 1，自下而上读 $(101111)_2$。"},
{topic: "base", difficulty: 2, type: "mcq", points: 2, q: "$(1011.101)_2$ 转十进制 = ?", options: ["11.625", "12.625", "10.5", "11.5"], answer: 0, explain: "$8+2+1+0.5+0.125 = 11.625$"},
{topic: "base", difficulty: 2, type: "fill", points: 2, q: "$(1101)_2$ 转十进制 = ?", answer: "13", explain: "$8+4+0+1 = 13$"},
{topic: "base", difficulty: 2, type: "mcq", points: 2, q: "$(0.625)_{10}$ 转二进制 = ?", options: ["$(0.101)_2$", "$(0.110)_2$", "$(0.111)_2$", "$(0.011)_2$"], answer: 0, explain: "$0.625\\times 2=1.25 → 1$；$0.25\\times 2=0.5 → 0$；$0.5\\times 2=1.0 → 1$。"},
{topic: "base", difficulty: 3, type: "fill", points: 3, q: "$(2AC.B)_{16}$ 转二进制（不含小数点前导 0 限制）", answer: "1010101100.1011", explain: "每位十六进制 → 4 位：$2=0010, A=1010, C=1100, B=1011$。"},
{topic: "base", difficulty: 3, type: "judge", points: 2, q: "$5/8$ 在二进制中有有限表示。", answer: true, explain: "$8 = 2^3$；分母质因子 $\\{2\\} \\subseteq \\{2\\}$ ⇒ 有限。"},
{topic: "base", difficulty: 3, type: "judge", points: 2, q: "$1/3$ 在十进制中有有限表示。", answer: false, explain: "分母含 3 ∉ {2,5}。"},
{topic: "base", difficulty: 3, type: "mcq", points: 2, q: "下列哪个分数在二进制中无有限表示？", options: ["$1/16$", "$3/8$", "$1/5$", "$7/4$"], answer: 2, explain: "$1/5$ 分母含 5 ∉ {2}。"},
{topic: "base", difficulty: 3, type: "judge", points: 2, q: "$(0.408)_{10}$ 在二进制中有有限表示。", answer: false, explain: "$0.408 = 51/125$；$125=5^3$ ⇒ 无限。"},
{topic: "base", difficulty: 3, type: "mcq-multi", points: 3, q: "下列哪些数在六进制中有有限表示？", options: ["$1/3$", "$1/4$", "$1/9$", "$5/12$"], answer: [0, 2, 3], explain: "$6 = 2\\times 3$；$1/3$ ✓；$1/4 = 1/2^2$，需 4 ∉ 因子集 ✗；$1/9 = 1/3^2$ ✓；$5/12 = 5/(2^2\\cdot 3)$ ✓。"},
{topic: "base", difficulty: 4, type: "fill", points: 3, q: "$(0.2)_8$ 转二进制 = ?", answer: "0.010", explain: "$2_8 = (010)_2$。"},
{topic: "base", difficulty: 4, type: "fill", points: 3, q: "$(0.65625)_{10}$ 转二进制（精度 $2^{-5}$）= ?", answer: "0.10101", explain: "$0.65625\\times 2 = 1.3125 → 1$；$0.3125\\times 2 = 0.625 → 0$；$0.625\\times 2 = 1.25 → 1$；$0.25\\times 2 = 0.5 → 0$；$0.5\\times 2 = 1 → 1$。"},
{topic: "base", difficulty: 5, type: "subjective", points: 4, q: "为何 $(0.1)_{10}$ 在二进制中无限循环？与浮点舍入误差有何关系？", answer: "分母 $10 = 2\\cdot 5$ 含 5 ⇒ 无限循环。浮点舍入截断 → 经典 $0.1+0.2 \\neq 0.3$。", explain: "$5 \\nmid 2$ ⇒ 无有限二进制；浮点必舍入，累积误差。"},
{topic: "base", difficulty: 5, type: "subjective", points: 4, q: "证明 $(0.\\overline{142857})_{10} = 1/7$ 并判断在二进制中是否有限。", answer: "$x = 142857/999999 = 1/7$；$7 \\nmid 2$ ⇒ 二进制无限。", explain: "周期 6 ⇒ 分母 $10^6-1 = 999999 = 7\\cdot 142857$。"},

{topic: "ca2", difficulty: 2, type: "fill", points: 2, q: "8 位补码表示范围（写成 $a, b$ 形式）：", answer: "-128,127", explain: "$[-2^{k-1}, 2^{k-1}-1]$。"},
{topic: "ca2", difficulty: 2, type: "mcq", points: 2, q: "$+42$ 的 8 位 CA2 = ?", options: ["00101010", "10101010", "11010110", "01010101"], answer: 0, explain: "正数直接二进制。"},
{topic: "ca2", difficulty: 2, type: "fill", points: 2, q: "$-42$ 的 8 位 CA2 = ?", answer: "11010110", explain: "$42=00101010$；取反 $11010101$；+1 $11010110$。"},
{topic: "ca2", difficulty: 2, type: "mcq", points: 2, q: "16 位 CA2 范围 = ?", options: ["$[-32768, 32767]$", "$[-32767, 32768]$", "$[-65536, 65535]$", "$[-32768, 32768]$"], answer: 0, explain: "$[-2^{15}, 2^{15}-1]$。"},
{topic: "ca2", difficulty: 3, type: "judge", points: 2, q: "CA2 自反性 $\\text{CA2}(\\text{CA2}(x)) = x$ 对所有 8 位值成立。", answer: true, explain: "取反 + 1 两次回到原值（mod $2^8$ 自动）。"},
{topic: "ca2", difficulty: 3, type: "mcq", points: 3, q: "8 位 CA2 码 $(11110000)_2$ 对应十进制 = ?", options: ["-16", "-240", "-128", "-15"], answer: 0, explain: "首位 1 → 取反+1：$(00010000) = 16$ ⇒ $-16$。"},
{topic: "ca2", difficulty: 3, type: "judge", points: 2, q: "8 位 CA2 中 $-64 + (-64)$ 会溢出。", answer: false, explain: "$-128 \\in [-128, 127]$ 可表 ⇒ 不溢出。$11000000 + 11000000 = 1\\,10000000$ 截 $10000000 = -128$。"},
{topic: "ca2", difficulty: 3, type: "mcq", points: 3, q: "下列 8 位 CA2 加法哪个会溢出？", options: ["$+50 + (-30)$", "$+70 + (+60)$", "$-70 + (-60)$", "$+100 + (-100)$"], answer: 1, explain: "$130 > 127$；同号正+正变负 ⇒ 溢出。" },
{topic: "ca2", difficulty: 4, type: "fill", points: 3, q: "8 位 CA2 中 $35 + (-28)$ 结果（二进制）= ?", answer: "00000111", explain: "$35 + (-28) = 7$；异号永不溢；二进制 $0000\\,0111$。"},
{topic: "ca2", difficulty: 4, type: "mcq-multi", points: 3, q: "8 位 CA2 下列说法哪些正确？", options: ["范围 $[0, 255]$", "最小负数 $-128$", "最大正数 $127$", "存在两个零"], answer: [1, 2], explain: "范围 $[-128,127]$；只有一个 0。"},
{topic: "ca2", difficulty: 4, type: "fill", points: 3, q: "$-24$ 的 8 位 CA2 符号扩展到 16 位 = ?", answer: "1111111111101000", explain: "8 位 $-24 = 11101000$；扩展左侧补符号位 1。"},
{topic: "ca2", difficulty: 4, type: "judge", points: 2, q: "8 位 CA2 中 $-128$ 有对应的正数 $+128$。", answer: false, explain: "$+128 \\notin [-128, 127]$（CA2 不对称）。"},
{topic: "ca2", difficulty: 5, type: "subjective", points: 4, q: "为何 8 位 CA2 范围不对称？给 $k$ 位通用公式。", answer: "范围 $[-2^{k-1}, 2^{k-1}-1]$；$2^k$ 个值分正负，0 归非负 ⇒ 负数比正数多 1。", explain: "0 归正端导致负方向多一个值。"},
{topic: "ca2", difficulty: 5, type: "subjective", points: 4, q: "12 位 CA2 加法溢出检测器逻辑。", answer: "若两输入同号但输出异号 ⇒ 溢出；等价于最高两位进位异或 $C_{n-1} \\oplus C_n = 1$。", explain: "硬件常用最高两位进位异或检测，效率高。"},

{topic: "float", difficulty: 2, type: "mcq", points: 2, q: "IEEE 单精度（32 位）结构 = ?", options: ["1+8+23", "1+11+52", "1+7+24", "1+9+22"], answer: 0, explain: "符号 1 + 指数 8 + 尾数 23。"},
{topic: "float", difficulty: 2, type: "fill", points: 2, q: "IEEE 32 位浮点 bias = ?", answer: "127", explain: "$2^{8-1} - 1 = 127$。"},
{topic: "float", difficulty: 2, type: "mcq", points: 2, q: "IEEE 64 位浮点有效尾数（含隐含位）宽度 = ?", options: ["52 位", "53 位", "51 位", "64 位"], answer: 1, explain: "隐含 1 + 存储 52 = 53。"},
{topic: "float", difficulty: 3, type: "judge", points: 2, q: "IEEE 浮点中指数全 0、尾数全 0 表示 0。", answer: true, explain: "符号位 0 或 1 ⇒ $+0$ 或 $-0$。"},
{topic: "float", difficulty: 3, type: "mcq", points: 3, q: "IEEE 32 位编码哪个表示 NaN？", options: ["指数全 1、尾数全 0", "指数全 1、尾数非 0", "指数全 0、尾数非 0", "指数 128、尾数全 0"], answer: 1, explain: "指数全 1 + 尾数 0 = $\\pm\\infty$；指数全 1 + 尾数非 0 = NaN。"},
{topic: "float", difficulty: 3, type: "judge", points: 2, q: "IEEE 浮点非规约数（denormal）出现在指数全 0 且尾数非 0 时。", answer: true, explain: "用于平滑过渡到 0。"},
{topic: "float", difficulty: 3, type: "mcq-multi", points: 3, q: "IEEE 32 位 $00000000\\ldots$ 与 $10000000\\ldots$（其余全 0）分别表示？", options: ["第一个是 +0", "第二个是 −0", "都表示 0（值相等）", "是最大和最小"], answer: [0, 1, 2], explain: "$+0$ 与 $-0$ 在比较中相等。"},
{topic: "float", difficulty: 4, type: "fill", points: 3, q: "IEEE 32 位最小正规约数 ≈ $2^{?}$（填指数）", answer: "-126", explain: "$e_\\min = 1 - 127 = -126$。"},
{topic: "float", difficulty: 4, type: "mcq", points: 3, q: "IEEE 32 位浮点 overflow 时结果通常是？", options: ["舍入到最大", "$\\pm\\infty$", "NaN", "保持原值"], answer: 1, explain: "超出最大可表数 ⇒ $\\pm\\infty$。"},
{topic: "float", difficulty: 4, type: "judge", points: 2, q: "浮点加法满足结合律。", answer: false, explain: "因舍入误差非结合，例 $(10^{20}+1)-10^{20} \\neq 10^{20}+(1-10^{20})$。"},
{topic: "float", difficulty: 4, type: "fill", points: 3, q: "浮点中大数 + 小数（差超 ULP）时小数被吞没；$a+b$ ≈ ?（填变量）", answer: "a", explain: "对齐时小数尾数被截 ⇒ $a + b = a$。"},
{topic: "float", difficulty: 4, type: "subjective", points: 4, q: "解释 IEEE 浮点隐含位的作用。", answer: "规约数最高位恒为 1，不存储以省 1 bit；存储 23 位 + 隐含 1 = 24 位有效，精度提升 1 bit。", explain: "前提是规约数 $m \\in [1, 2)$。"},
{topic: "float", difficulty: 5, type: "mcq", points: 4, q: "下列哪个浮点计算会因舍入产生反直觉结果？", options: ["$0.1 + 0.2 = 0.3$", "$(a+b)+c = a+(b+c)$ 总成立", "$10^{20}+1-10^{20} = 0$", "正数累加 > 0"], answer: 2, explain: "$10^{20}$ 量级时 1 被吞没。"},
{topic: "float", difficulty: 5, type: "subjective", points: 4, q: "$0.1 \\times 10 \\times 100$ 与 $0.1 \\times 1000$ 哪个更精确？", answer: "前者更易累积误差；后者一次乘法误差更小。一般从大量级到小量级或反之要规划顺序。", explain: "浮点乘法非可交换性导致中间结果舍入差异。"},
{topic: "float", difficulty: 5, type: "fill", points: 4, q: "IEEE 32 位机器精度 $\\varepsilon_\\text{mach} = 2^{?}$", answer: "-23", explain: "尾数 23 位 ⇒ $\\varepsilon = 2^{-23} \\approx 1.19\\times 10^{-7}$。"},

/* === 段 B：布尔 / Karnaugh / Beth === */
{topic: "boolean", difficulty: 3, type: "fill", points: 3, q: "化简 $a(a+b) + b(a+b)$。", answer: "a+b", explain: "$(a+b)(a+b) = a+b$（幂等律）。"},
{topic: "boolean", difficulty: 2, type: "judge", points: 2, q: "$\\overline{ab+c} = \\overline a + \\overline b \\cdot \\overline c$", answer: false, explain: "正确为 $\\overline{ab+c} = (\\overline a + \\overline b)\\cdot \\overline c$。"},
{topic: "boolean", difficulty: 3, type: "fill", points: 3, q: "$(a + \\overline b)(\\overline a + c)(b + \\overline c)$ 真值表中为真的行数 = ?", answer: "2", explain: "枚举 8 行真值表得 2 个为真组合。"},
{topic: "boolean", difficulty: 4, type: "mcq", points: 3, q: "化简 $ab + \\overline a b + \\overline a \\overline b$ = ?", options: ["$\\overline a$", "$a+b$", "$\\overline a + b$", "$\\overline{ab}$"], answer: 2, explain: "$= b + \\overline a \\overline b = b + \\overline a$。"},
{topic: "boolean", difficulty: 3, type: "fill", points: 2, q: "$\\overline{\\overline a + b}\\cdot c$ 化简（无嵌套否定）= ?", answer: "a b̄ c", explain: "De Morgan：$\\overline{\\overline a + b} = a\\overline b$。"},
{topic: "boolean", difficulty: 2, type: "mcq", points: 2, q: "下列哪个**不是**重言式？", options: ["$a + \\overline a$", "$ab + \\overline a + \\overline b$", "$a \\to (a + b)$", "$\\overline{(ab)\\to(a+b)}$"], answer: 3, explain: "$ab \\to a+b$ 恒真 ⇒ 其否定恒假，不是重言式。"},
{topic: "boolean", difficulty: 4, type: "fill", points: 3, q: "$(a + \\overline b)(\\overline a + b)$ 的 minterm（写成 $m_i$ 求和形式）= ?", answer: "m0 + m3", explain: "真值表中 $f=1$：$(a,b)=(0,0)$ 即 $m_0$，$(1,1)$ 即 $m_3$。"},
{topic: "boolean", difficulty: 3, type: "mcq-multi", points: 3, q: "下列哪些操作保持布尔等价？", options: ["对所有变量同时取否", "用 De Morgan 展开否定", "$a\\to b$ 替换为 $\\overline a + b$", "交换合取项顺序"], answer: [1, 2, 3], explain: "对所有变量同时取否一般**不**保持等价（除非函数自对偶）。"},
{topic: "boolean", difficulty: 5, type: "subjective", points: 4, q: "给 $f = \\overline a bc + a\\overline b c + abc$，求 FND 与 FNC。", answer: "FND = $\\overline a bc + a\\overline b c + abc$；FNC 可从 $f=0$ 行构造。", explain: "FND 直接读 1 行；FNC 读 0 行（每项对值取反）。"},
{topic: "boolean", difficulty: 2, type: "judge", points: 2, q: "$a + a = a$ 和 $a + 0 = a$ 是布尔代数公理。", answer: true, explain: "幂等律 + 单位元。"},
{topic: "boolean", difficulty: 3, type: "fill", points: 3, q: "化简 $\\overline a\\overline b\\overline c + \\overline a\\overline bc + \\overline a bc + abc$ = ?", answer: "ā b̄ + bc", explain: "$\\overline a\\overline b(\\overline c + c) + bc(\\overline a + a) = \\overline a\\overline b + bc$。"},
{topic: "boolean", difficulty: 4, type: "mcq", points: 3, q: "$F = (a\\to b)\\land(b\\to c)\\land\\neg c$ 为真的赋值有几个？", options: ["0", "1", "2", "3"], answer: 1, explain: "$\\neg c\\Rightarrow c=0$；$b\\to c\\Rightarrow b=0$；$a\\to b\\Rightarrow a=0$。唯一解 $(0,0,0)$。"},
{topic: "boolean", difficulty: 3, type: "fill", points: 2, q: "对 $E = a(\\overline b + c)$ 应用分配律 = ?", answer: "a b̄ + ac", explain: "标准分配律。"},
{topic: "boolean", difficulty: 2, type: "mcq", points: 2, q: "下列哪个恒等式**错误**？", options: ["$a + ab = a$", "$aa = a$", "$a+b = \\overline{\\overline a\\overline b}$", "$a\\to b = a + b$"], answer: 3, explain: "$a\\to b \\equiv \\overline a + b$，不是 $a+b$。"},
{topic: "boolean", difficulty: 4, type: "fill", points: 3, q: "$f = 0$ 在 $(0,0,0),(0,1,0),(1,0,0)$；其 FNC 最简（化简后）= ?", answer: "(a+c)(b̄+c)", explain: "公共特征 $c=0$ 部分约束，结合最简。"},
{topic: "boolean", difficulty: 3, type: "judge", points: 2, q: "$\\overline{(ab)\\lor(cd)} = (\\overline a\\lor\\overline b)\\land(\\overline c\\lor\\overline d)$", answer: true, explain: "外层 De Morgan + 内层各自展开。"},

{topic: "karnaugh", difficulty: 2, type: "fill", points: 2, q: "4 变量 K-map 行（ab）按格雷码：00, ?, 11, 10。问号 = ?", answer: "01", explain: "格雷码序列。"},
{topic: "karnaugh", difficulty: 3, type: "mcq", points: 3, q: "K-map 分组规则下列哪个**错**？", options: ["分组必须为矩形", "分组大小必须 $2^k$", "同一个 1 可在多分组", "对角格可在同分组"], answer: 3, explain: "K-map 仅按边相邻；对角不能直接相圈。"},
{topic: "karnaugh", difficulty: 4, type: "mcq", points: 3, q: "4 变量 K-map 单项最大有效圈 = ?", options: ["4", "8", "16", "取决于函数"], answer: 1, explain: "16 = 常 1；最大单 littéral 圈 = 8 = $2^3$。"},
{topic: "karnaugh", difficulty: 3, type: "fill", points: 2, q: "5 变量 K-map 通常画为两张 4 变量表，跨页相邻指 = ?", answer: "两表对应位置", explain: "$e=0$ 与 $e=1$ 同位置视为相邻。"},
{topic: "karnaugh", difficulty: 2, type: "judge", points: 2, q: "K-map 中 don't-care 圈入分组后，最终公式对该位置输出确定。", answer: true, explain: "化简后表达式确定，don't-care 仅化简过程灵活。"},
{topic: "karnaugh", difficulty: 3, type: "mcq-multi", points: 3, q: "K-map 中 don't-care 用法正确的有？", options: ["可视为 1 扩大圈", "可视为 0 避免某项", "× 必须被覆盖", "× 可不全覆盖"], answer: [0, 1, 3], explain: "× 不强制覆盖，仅 1 必须覆盖。"},
{topic: "karnaugh", difficulty: 3, type: "judge", points: 2, q: "FNC 在 K-map 中通过圈 0 读出，每项是析取。", answer: true, explain: "FNC 外层合取，内层析取。"},
{topic: "karnaugh", difficulty: 2, type: "judge", points: 2, q: "3 变量 K-map 中 $(a,b,c)=(0,1,1)$ 编号为 $m_3$。", answer: true, explain: "二进制 011 = 3。"},
{topic: "karnaugh", difficulty: 3, type: "mcq", points: 3, q: "4 变量 K-map 四角格子之间相邻关系？", options: ["完全不相邻", "两两相邻", "仅上下或左右", "四角构成一个连通分组"], answer: 3, explain: "环面拓扑使四角相邻。"},
{topic: "karnaugh", difficulty: 4, type: "fill", points: 3, q: "5 变量 K-map 跨两页的最大矩形分组 = ?（格子数）", answer: "16", explain: "每页最多 8（共 16 格中半数），跨页合并最多 16。"},
{topic: "karnaugh", difficulty: 3, type: "fill", points: 2, q: "K-map 用格雷码的主要优势 = ?", answer: "保证相邻格仅 1 位差异", explain: "便于直观找最大矩形。"},

{topic: "beth", difficulty: 2, type: "judge", points: 2, q: "Beth 树中 α 规则不分叉，β 规则分叉。", answer: true, explain: "α: ∧, ¬∨, ¬→；β: ∨, →, ↔, ¬∧。"},
{topic: "beth", difficulty: 3, type: "fill", points: 2, q: "对 $\\neg(a\\land b)$ Beth 树用何规则？分支 = ?", answer: "β; ¬a | ¬b", explain: "$\\neg(\\land)$ 是 β 规则。"},
{topic: "beth", difficulty: 4, type: "judge", points: 3, q: "若 $\\Sigma\\cup\\{\\neg F\\}$ 的 Beth 树全闭，则 $\\Sigma \\models F$。", answer: true, explain: "无反模型 ⇒ 蕴含成立。"},
{topic: "beth", difficulty: 3, type: "judge", points: 2, q: "Beth 树支闭合 ⇔ 出现 $p$ 与 $\\neg p$ 矛盾。", answer: true, explain: "矛盾字面量定义。"},
{topic: "beth", difficulty: 3, type: "mcq", points: 3, q: "$a \\to (b \\lor c)$ 的 Beth 树第一步分支 = ?", options: ["$\\neg a$ 单支", "$b\\lor c$ 单支", "$\\neg a$ | $(b\\lor c)$", "$a \\land \\neg(b\\lor c)$"], answer: 2, explain: "$\\to$ 是 β 规则。"},
{topic: "beth", difficulty: 2, type: "fill", points: 2, q: "Beth 树中含 $p$ 与 $\\neg p$ 的支称 = ?", answer: "闭支", explain: "Closed branch / closed."},
{topic: "beth", difficulty: 4, type: "mcq-multi", points: 3, q: "$F$ 是重言式 ⇔ 下列哪些等价？", options: ["真值表全 1", "$\\{\\neg F\\}$ 的 Beth 树全闭", "所有赋值满足", "$\\models F$"], answer: [0, 1, 2, 3], explain: "都是等价刻画。"},
{topic: "beth", difficulty: 3, type: "fill", points: 3, q: "证 $\\{p, p\\to q\\}\\models q$：加 $\\neg q$，β 拆 $p\\to q$ 得 = ?", answer: "¬p | q", explain: "两支均闭：$\\neg p$ 与 $p$，$q$ 与 $\\neg q$。"},
{topic: "beth", difficulty: 4, type: "judge", points: 2, q: "Beth 树中遇 $\\neg\\neg a$ 应用双否消除得 $a$（α 规则）。", answer: true, explain: "$\\neg\\neg$ 化简为原子。"},
{topic: "beth", difficulty: 3, type: "fill", points: 2, q: "$\\neg(a\\leftrightarrow b)$ 是何类型？分支 = ?", answer: "β; (a∧¬b) | (¬a∧b)", explain: "等价的否定 = 异或。"},
{topic: "beth", difficulty: 5, type: "subjective", points: 4, q: "用 Beth 验证 $\\{a\\lor b, \\neg a\\to c\\} \\models b\\lor c$。", answer: "假设 $\\neg b, \\neg c$；β $a\\lor b$：$a$ 支由 $\\neg a\\to c$ + $\\neg c$ 推 $a$ 矛盾；$b$ 支与 $\\neg b$ 矛盾。全闭。", explain: "经典分情况推理。"},
{topic: "beth", difficulty: 4, type: "mcq", points: 3, q: "Beth 树某支已闭后，应：", options: ["继续穷尽展开", "停止该支", "分裂新支", "交语义"], answer: 1, explain: "闭支即矛盾，无需展开。"},
{topic: "beth", difficulty: 2, type: "fill", points: 2, q: "α 规则代表形式有 $a\\land b$ 和 = ?", answer: "¬(a∨b) 或 ¬(a→b)", explain: "α: ∧, ¬∨, ¬→, ¬¬。"},
{topic: "beth", difficulty: 2, type: "mcq", points: 2, q: "$\\neg(p\\to q)$ 展开后字面量 = ?", options: ["$\\neg p, \\neg q$", "$p, \\neg q$", "$\\neg p, q$", "$p, q$"], answer: 1, explain: "$\\neg(p\\to q) = p \\land \\neg q$。"},
{topic: "boolean", difficulty: 4, type: "mcq", points: 3, q: "$f = ab + \\overline a\\overline c + bc$ 化简后**不**等价的是？", options: ["$ab + \\overline a\\overline c$", "$b + \\overline a\\overline c$", "$ab + \\overline c$", "$\\overline a\\overline c + bc$"], answer: 2, explain: "$ab + \\overline c$ 缺少 $bc$ 在 $a=1, b=0, c=0$ 时的覆盖。"},
{topic: "boolean", difficulty: 2, type: "fill", points: 2, q: "$a + \\overline a b = a + b$ 称 = ?", answer: "吸收律", explain: "Absorption。"},
{topic: "beth", difficulty: 3, type: "fill", points: 3, q: "证 $\\vdash (a\\to b)\\lor(b\\to a)$ Beth 树第一步 = ?", answer: "对 ¬F 应用 ¬∨（α）展开为 ¬(a→b) 与 ¬(b→a)", explain: "都得 $a, \\neg b$ 与 $b, \\neg a$ 同时存在 ⇒ 矛盾。"},
{topic: "boolean", difficulty: 2, type: "mcq", points: 2, q: "布尔代数中 0 和 1 分别表示？", options: ["真 假", "假 真", "空 全", "否 是"], answer: 1, explain: "$1 = T$, $0 = F$。"},
{topic: "boolean", difficulty: 5, type: "subjective", points: 4, q: "证 De Morgan 律对 3 个变量：$\\overline{abc} = \\overline a + \\overline b + \\overline c$。", answer: "$\\overline{abc} = \\overline{(ab)c} = \\overline{ab} + \\overline c = \\overline a + \\overline b + \\overline c$（递归用 2 元 De Morgan）。", explain: "n 元归纳。"},
{topic: "karnaugh", difficulty: 4, type: "fill", points: 3, q: "5 变量 K-map 中两页对应位置 4 元矩形分组合并后消去的变量 = ?", answer: "e", explain: "$e=0$ 与 $e=1$ 都覆盖 ⇒ 消去 $e$。"},
{topic: "boolean", difficulty: 3, type: "judge", points: 2, q: "$\\overline{a+b}\\cdot c = \\overline a c + \\overline b c$。", answer: false, explain: "$\\overline{a+b}\\cdot c = \\overline a\\overline b c$，不是和。"},
{topic: "beth", difficulty: 4, type: "mcq", points: 3, q: "$\\Sigma=\\{a\\to b, \\neg b\\}$ 验证 $\\models \\neg a$ 的 Beth 树关键步骤？", options: ["$\\neg a, \\neg b, a$ 三字面", "$b, \\neg a, \\neg b$ 三字面", "β 拆 $a\\to b$ 两支自闭", "$a, b$ 待分析"], answer: 2, explain: "$\\neg a$ 支与 $a$ 矛盾；$b$ 支与 $\\neg b$ 矛盾。"},

/* === 段 C：模运算 / RSA / 数论 === */
{topic: "modular", difficulty: 2, type: "mcq", points: 2, q: "$\\mathbb Z_{11}$ 中 $7 + 5 = ?$", options: ["12", "1", "0", "11"], answer: 1, explain: "$12 \\equiv 1 \\pmod{11}$。"},
{topic: "modular", difficulty: 2, type: "judge", points: 2, q: "若 $p$ 素数，$\\mathbb Z_p$ 中每个非零元都有逆元。", answer: true, explain: "Bézout：$\\gcd(k,p)=1$ 对所有 $1\\le k\\le p-1$。"},
{topic: "modular", difficulty: 3, type: "mcq", points: 3, q: "欧拉函数 $\\varphi(30) = ?$", options: ["12", "8", "10", "15"], answer: 1, explain: "$30 = 2\\cdot 3\\cdot 5$；$\\varphi = 30(1-1/2)(1-1/3)(1-1/5) = 8$。"},
{topic: "modular", difficulty: 3, type: "fill", points: 2, q: "$\\varphi(45) = ?$", answer: "24", explain: "$45 = 3^2 \\cdot 5$；$45\\cdot 2/3\\cdot 4/5 = 24$。"},
{topic: "modular", difficulty: 2, type: "judge", points: 2, q: "费马小定理：$2^{10} \\equiv 1 \\pmod{11}$。", answer: true, explain: "$11$ 素，$\\gcd(2,11)=1$。"},
{topic: "modular", difficulty: 3, type: "mcq", points: 3, q: "$3^{2024} \\bmod 7 = ?$", options: ["1", "3", "2", "4"], answer: 2, explain: "$3^6\\equiv 1$；$2024 = 337\\cdot 6 + 2$；$3^2 = 9 \\equiv 2$。"},
{topic: "modular", difficulty: 3, type: "judge", points: 2, q: "若 $\\gcd(a,n) = d > 1$，$ax\\equiv b\\pmod n$ 有解 ⇔ $d|b$。", answer: true, explain: "可解性定理。"},
{topic: "modular", difficulty: 3, type: "fill", points: 2, q: "$7^{100} \\bmod 15 = ?$", answer: "1", explain: "$\\varphi(15) = 8$；$100 = 12\\cdot 8 + 4$；$7^4 = 2401 = 160\\cdot 15 + 1 \\equiv 1$。"},
{topic: "modular", difficulty: 4, type: "subjective", points: 4, q: "证费马小定理：$p$ 素 ∧ $\\gcd(a,p)=1$ ⇒ $a^{p-1}\\equiv 1\\pmod p$。", answer: "由欧拉定理，$\\varphi(p)=p-1$；$a^{\\varphi(p)} = a^{p-1} \\equiv 1 \\pmod p$。", explain: "费马是欧拉在素数情形的特例。"},
{topic: "modular", difficulty: 3, type: "mcq", points: 2, q: "$\\mathbb Z_{13}$ 中 $2^{-1}\\cdot 3^{-1} = ?$", options: ["$6^{-1}$", "$18^{-1}$", "$5^{-1}$", "$8$"], answer: 0, explain: "$(ab)^{-1} = a^{-1}b^{-1}$。"},
{topic: "modular", difficulty: 2, type: "fill", points: 2, q: "$\\varphi(100) = ?$", answer: "40", explain: "$100 = 2^2\\cdot 5^2$；$100\\cdot 1/2\\cdot 4/5 = 40$。"},
{topic: "modular", difficulty: 3, type: "judge", points: 2, q: "$\\mathbb Z_6$ 中 $3x\\equiv 3\\pmod 6$ 有唯一解。", answer: false, explain: "$\\gcd(3,6)=3$ ⇒ 3 个解：$\\{1,3,5\\}$。"},
{topic: "modular", difficulty: 4, type: "fill", points: 3, q: "$9^{-1} \\bmod 26 = ?$", answer: "3", explain: "扩欧：$1 = 3\\cdot 9 - 26$ ⇒ $9^{-1}\\equiv 3$。"},
{topic: "modular", difficulty: 3, type: "mcq", points: 2, q: "$n = pq$（$p,q$ 素），$\\varphi(n) = ?$", options: ["$(p-1)(q-1)$", "$n-1$", "$(p-1)q$", "$pq$"], answer: 0, explain: "Euler 函数乘性。"},
{topic: "modular", difficulty: 2, type: "fill", points: 2, q: "$-5 \\bmod 12$ 的标准代表元 = ?", answer: "7", explain: "$-5 + 12 = 7$。"},
{topic: "modular", difficulty: 3, type: "fill", points: 2, q: "$2^{-1} \\bmod 19 = ?$", answer: "10", explain: "$2\\cdot 10 = 20 \\equiv 1\\pmod{19}$。"},
{topic: "modular", difficulty: 3, type: "judge", points: 2, q: "$\\mathbb Z_{15}$ 是整环。", answer: false, explain: "$3\\cdot 5\\equiv 0$ 但 $3, 5\\not\\equiv 0$ ⇒ 有零因子。"},

{topic: "rsa", difficulty: 2, type: "fill", points: 2, q: "RSA 中 $p=3, q=11, e=3$；$\\varphi(n) = ?$", answer: "20", explain: "$(3-1)(11-1) = 20$。"},
{topic: "rsa", difficulty: 3, type: "fill", points: 3, q: "续上：$d = ?$（$ed\\equiv 1\\pmod{\\varphi}$）", answer: "7", explain: "$3\\cdot 7 = 21\\equiv 1\\pmod{20}$。"},
{topic: "rsa", difficulty: 2, type: "judge", points: 2, q: "RSA 私钥 $d$ 满足 $ed\\equiv 1\\pmod n$。", answer: false, explain: "应是 mod $\\varphi(n)$，**不是** mod $n$（高频陷阱）。"},
{topic: "rsa", difficulty: 3, type: "fill", points: 2, q: "RSA $m=5, e=3, n=33$；$c = ?$", answer: "26", explain: "$5^3 = 125 = 3\\cdot 33 + 26 \\equiv 26\\pmod{33}$。"},
{topic: "rsa", difficulty: 4, type: "mcq-multi", points: 3, q: "关于 RSA，下列哪些正确？", options: ["公钥 $(n,e)$，私钥 $(n,d)$", "$\\gcd(e,\\varphi(n))=1$", "$c \\equiv m^e\\pmod n$", "$d \\equiv e^{-1}\\pmod n$"], answer: [0, 1, 2], explain: "(D) 错：$d \\equiv e^{-1}\\pmod{\\varphi(n)}$。"},
{topic: "rsa", difficulty: 2, type: "fill", points: 2, q: "RSA $p=5, q=7, e=5$；公钥 = ?（写成 (n,e)）", answer: "(35,5)", explain: "$n = pq = 35$。"},
{topic: "rsa", difficulty: 3, type: "fill", points: 3, q: "续上：$d = ?$", answer: "29", explain: "$\\varphi=24$；$5\\cdot 29 = 145 = 6\\cdot 24 + 1\\equiv 1$。"},
{topic: "rsa", difficulty: 4, type: "subjective", points: 4, q: "为何 RSA 中 $d$ 必须满足 $ed\\equiv 1\\pmod{\\varphi(n)}$ 而非 mod $n$？", answer: "解密 $c^d = m^{ed} = m^{1+k\\varphi(n)} = m\\cdot(m^{\\varphi(n)})^k \\equiv m\\pmod n$（欧拉定理）。仅 mod $\\varphi$ 才能消去额外指数。", explain: "mod $n$ 无周期保证，解密失败。"},
{topic: "rsa", difficulty: 3, type: "judge", points: 2, q: "RSA 中若攻击者知 $\\varphi(n)$ 和 $n$，可分解 $n = pq$。", answer: true, explain: "由 $p+q = n - \\varphi + 1$ 与 $pq = n$ 解二次方程。"},
{topic: "rsa", difficulty: 4, type: "fill", points: 3, q: "小模数 RSA $n = 91$。$\\varphi(n) = ?$", answer: "72", explain: "$91 = 7\\cdot 13$；$\\varphi = 6\\cdot 12 = 72$。"},
{topic: "rsa", difficulty: 4, type: "fill", points: 3, q: "续上 $e = 7$；$d = ?$", answer: "31", explain: "$7\\cdot 31 = 217 = 3\\cdot 72 + 1$。"},
{topic: "rsa", difficulty: 3, type: "mcq", points: 2, q: "RSA 安全性主要基于：", options: ["乘法难", "大数分解难", "模运算复杂", "指数增长"], answer: 1, explain: "因式分解 $n = pq$ 的计算困难性。"},
{topic: "rsa", difficulty: 4, type: "subjective", points: 4, q: "RSA 中小指数 $e = 3$ 的风险及防范？", answer: "若多用户用 $e=3$ 加密同明文 $m$，攻击者用 CRT 从 3 个密文恢复 $m^3$，再开立方得 $m$。防范：OAEP padding。", explain: "已知攻击向量。"},

{topic: "numtheory", difficulty: 2, type: "fill", points: 2, q: "$\\gcd(36, 60) = ?$", answer: "12", explain: "$60 = 1\\cdot 36 + 24$；$36 = 1\\cdot 24 + 12$；$24 = 2\\cdot 12$ ⇒ 12。"},
{topic: "numtheory", difficulty: 2, type: "fill", points: 2, q: "$\\gcd(17, 5) = ?$", answer: "1", explain: "$17 = 3\\cdot 5 + 2$；$5 = 2\\cdot 2 + 1$；$2 = 2\\cdot 1$。"},
{topic: "numtheory", difficulty: 3, type: "fill", points: 3, q: "$\\text{lcm}(12, 18) = ?$", answer: "36", explain: "$\\gcd = 6$；$12\\cdot 18/6 = 36$。"},
{topic: "numtheory", difficulty: 3, type: "judge", points: 2, q: "若 $a|b$ 且 $b|c$，则 $a|c$。", answer: true, explain: "整除传递性。"},
{topic: "numtheory", difficulty: 3, type: "mcq", points: 2, q: "$\\gcd(a,b)\\cdot\\text{lcm}(a,b) = ?$", options: ["$ab$", "$a+b$", "$|a-b|$", "$2ab$"], answer: 0, explain: "基本恒等式。"},
{topic: "numtheory", difficulty: 4, type: "fill", points: 3, q: "扩欧求 $\\gcd(13, 8)$ 的 Bézout 系数 $13x + 8y = 1$；$x = ?$", answer: "-3", explain: "$1 = 5\\cdot 8 - 3\\cdot 13$ ⇒ $x = -3, y = 5$。"},
{topic: "numtheory", difficulty: 3, type: "judge", points: 2, q: "若 $\\gcd(a,n) = 1$ 且 $\\gcd(b,n) = 1$，则 $\\gcd(ab,n) = 1$。", answer: true, explain: "素因子分解论证。"},
{topic: "numtheory", difficulty: 4, type: "subjective", points: 4, q: "证 Bézout 引理：$d = \\gcd(a,b) \\Rightarrow \\exists x,y$ 使 $ax + by = d$。", answer: "用扩展欧几里得算法逐步回代余数；最终 $d$ 表为 $a, b$ 的整线性组合。", explain: "扩欧的理论基础。"},
{topic: "numtheory", difficulty: 3, type: "mcq-multi", points: 3, q: "下列 gcd 性质哪些正确？", options: ["$\\gcd(a,0) = a$", "$\\gcd(a,b) = \\gcd(b, a\\bmod b)$", "$\\gcd(ka,kb) = k\\gcd(a,b)$", "$\\gcd(\\gcd(a,b),c) = \\gcd(a,\\gcd(b,c))$"], answer: [0, 1, 2, 3], explain: "全是 gcd 基本性质。"},
{topic: "numtheory", difficulty: 3, type: "fill", points: 2, q: "CRT：$x\\equiv 1\\pmod 3, x\\equiv 2\\pmod 5$；最小正解 = ?", answer: "7", explain: "$x = 1 + 3t$；$3t\\equiv 1\\pmod 5$ ⇒ $t = 2$；$x = 7$。"},
{topic: "numtheory", difficulty: 4, type: "fill", points: 3, q: "CRT：$x\\equiv 2\\pmod 7, x\\equiv 3\\pmod{11}$；最小正解 = ?", answer: "58", explain: "$x = 2 + 7k$；$2 + 7k\\equiv 3\\pmod{11}$ ⇒ $7k\\equiv 1$ ⇒ $k\\equiv 8$；$x = 58$。"},
{topic: "numtheory", difficulty: 3, type: "judge", points: 2, q: "CRT 要求模数两两互素。", answer: true, explain: "否则系统可能无解或非唯一。"},
{topic: "numtheory", difficulty: 4, type: "fill", points: 3, q: "证 $6 | n(n^2 - 1)$ 关键 = ?", answer: "n(n-1)(n+1) 为连续 3 整数，含 2 和 3 的倍数", explain: "$\\text{lcm}(2,3) = 6$。"},
{topic: "numtheory", difficulty: 2, type: "judge", points: 2, q: "若 $p|ab$ 且 $p$ 素，则 $p|a$ 或 $p|b$。", answer: true, explain: "素数定义性质（Euclid 引理）。"},
{topic: "numtheory", difficulty: 3, type: "subjective", points: 4, q: "证素数无穷多。", answer: "假设有限：$p_1,\\ldots,p_k$；取 $N = p_1\\cdots p_k + 1$；$N$ 不被任 $p_i$ 整除 ⇒ 存在新素因子，矛盾。", explain: "Euclid 经典证明。"},
{topic: "numtheory", difficulty: 3, type: "fill", points: 2, q: "$\\mathbb Z_n$ 中可逆元个数 = ?", answer: "φ(n)", explain: "可逆 ⇔ $\\gcd = 1$。"},
{topic: "numtheory", difficulty: 4, type: "mcq-multi", points: 3, q: "下列整除命题哪些正确？", options: ["$a|b, b|c \\Rightarrow a|c$", "$a|c, b|c \\Rightarrow ab|c$", "$a|b \\Rightarrow a|kab$（任意 $k$）", "$a|b, a|c \\Rightarrow a|(pb+qc)$"], answer: [0, 2, 3], explain: "(B) 需 $\\gcd(a,b)=1$。"},
{topic: "numtheory", difficulty: 2, type: "judge", points: 2, q: "若 $d|a$ 且 $d|b$，则 $d|\\gcd(a,b)$。", answer: true, explain: "公约数 ≤ 最大公约数。"},
{topic: "numtheory", difficulty: 3, type: "fill", points: 2, q: "$\\gcd(100, 35) = ?$", answer: "5", explain: "$100 = 2\\cdot 35 + 30$；$35 = 1\\cdot 30 + 5$；$30 = 6\\cdot 5$。"},
{topic: "numtheory", difficulty: 4, type: "fill", points: 3, q: "$2$ 模 $17$ 的阶 = ?", answer: "8", explain: "$2^8 = 256 = 15\\cdot 17 + 1\\equiv 1\\pmod{17}$；最小指数。"},
{topic: "numtheory", difficulty: 3, type: "judge", points: 2, q: "若 $n = pq$（$p, q$ 不同素），则 $\\varphi(n) = n - p - q + 1$。", answer: true, explain: "$(p-1)(q-1) = pq - p - q + 1$。"},
{topic: "numtheory", difficulty: 4, type: "subjective", points: 4, q: "费马小定理与欧拉定理的关系？", answer: "费马是欧拉在 $n = p$ 素数时的特例：$\\varphi(p) = p - 1$，故 $a^{p-1}\\equiv 1$。欧拉对一般 $n$ 也成立。", explain: "都用于模幂计算和 RSA。"}

];

if (typeof module !== "undefined") module.exports = NEWPOOL;
